### ISSUE TITLE
Remove MTDC?

### ISSUE THREAD

**Issue by davidchisnall** [CHERIoT-Platform/cheriot-sail#73] opened 2024-10-03 10:25 UTC
We originally used MScratchC in the switcher and then moved to using MTDC because we thought that MScratchC might go away.  In the Zcheripurecap spec, MScratchC is present and MTDC is not (it is in the hybrid extension).  Given that we don't use both registers, and we will likely remove MTDC in v2 for alignment with Zcheripurecap, it might be a good idea to remove it for v1.0.

**Comment by rmn30** [comment] 2024-10-03 12:45
This is a duplicate of https://github.com/CHERIoT-Platform/cheriot-sail/issues/21

**Comment by rmn30** [comment] 2024-10-03 12:56
Closing as duplicate.

**Comment by rmn30** [comment] 2024-10-03 12:58
Closing as duplicate of #21

**Closed by rmn30** 2024-10-03 12:58 UTC
Labels: duplicate
